# .readthedocs.yaml

version: 2

# Build documentation in the 'docs/' directory
sphinx:
  configuration: docs/conf.py

# Install your Python dependencies from the main requirements.txt
python:
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"