name: ML App CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        shell: bash

      - name: Train Model
        run: |
          python -m ml_app.train
        env:
          DATA: '[ [5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2] ]'

      - name: Save Model as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: trained-model
          path: out.json

      - name: Run Tests
        run: |
          source venv/bin/activate
          python -m pytest

      - name: Build Documentation
        run: |
          source venv/bin/activate
          sphinx-build -b html docs/ docs/_build

      - name: Upload Documentation to ReadTheDocs
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/_build


